import { Driver, Delivery } from './types';

export interface CityPricing {
  name: string;
  baseRate: number;
  isWithinCity: boolean;
}

export const CITIES_PRICING: CityPricing[] = [
  { name: 'Paulo Afonso - BA (Dentro da Cidade)', baseRate: 2.50, isWithinCity: true },
  { name: 'Delmiro Gouveia - AL', baseRate: 3.55, isWithinCity: false }, // Let's set the exact rates
  { name: 'Pariconha - AL', baseRate: 5.00, isWithinCity: false },
  { name: 'Água Branca - AL', baseRate: 5.00, isWithinCity: false },
  { name: 'Mata Grande - AL', baseRate: 3.50, isWithinCity: false },
  { name: 'Canindé de São Francisco - SE', baseRate: 5.00, isWithinCity: false },
  { name: 'Santa Brígida - BA', baseRate: 5.00, isWithinCity: false },
  { name: 'Jeremoabo - BA', baseRate: 5.00, isWithinCity: false },
  { name: 'Glória - BA', baseRate: 5.00, isWithinCity: false },
  { name: 'Jatobá - PE', baseRate: 5.00, isWithinCity: false },
  { name: 'Petrolândia - PE', baseRate: 5.00, isWithinCity: false },
  { name: 'Tacaratu - PE', baseRate: 5.00, isWithinCity: false },
];

// Fallback rates search
CITIES_PRICING[1].baseRate = 3.50; // Set Delmiro Gouveia to exactly 3.50 as requested by user

// The 15 Delivery Drivers (exactly 15)
export const INITIAL_DRIVERS: Driver[] = [
  {
    id: 'drv-1',
    name: 'Carlos "Vozinha" Silva',
    avatar: 'CS',
    vehicle: 'Moto',
    status: 'Em Trânsito',
    phone: '(75) 98122-3041',
    rating: 4.9,
    completedCount: 24,
  },
  {
    id: 'drv-2',
    name: 'Wander',
    avatar: 'W',
    vehicle: 'Moto',
    status: 'Disponível',
    phone: '(75) 97411-2098',
    rating: 4.8,
    completedCount: 18,
  },
  {
    id: 'drv-3',
    name: 'Lucas "Zulú" de Souza',
    avatar: 'LS',
    vehicle: 'Moto',
    status: 'Disponível',
    phone: '(75) 98555-4032',
    rating: 4.7,
    completedCount: 32,
  },
  {
    id: 'drv-4',
    name: 'Marcos Henrique Santos',
    avatar: 'MS',
    vehicle: 'Moto',
    status: 'Em Trânsito',
    phone: '(75) 96311-1254',
    rating: 4.9,
    completedCount: 45,
  },
  {
    id: 'drv-5',
    name: 'Juliana Ribeiro Costa',
    avatar: 'JC',
    vehicle: 'Carro',
    status: 'Pausa',
    phone: '(75) 99188-7521',
    rating: 4.6,
    completedCount: 15,
  },
  {
    id: 'drv-6',
    name: 'Rodrigo Pereira Lima',
    avatar: 'RL',
    vehicle: 'Bike',
    status: 'Disponível',
    phone: '(75) 97121-8832',
    rating: 4.5,
    completedCount: 12,
  },
  {
    id: 'drv-7',
    name: 'Felipe "Speed" Castelo',
    avatar: 'FC',
    vehicle: 'Moto',
    status: 'Disponível',
    phone: '(75) 99256-4321',
    rating: 4.9,
    completedCount: 50,
  },
  {
    id: 'drv-8',
    name: 'Bruno "Seta" Gomes',
    avatar: 'BG',
    vehicle: 'Moto',
    status: 'Em Trânsito',
    phone: '(75) 98877-1122',
    rating: 4.8,
    completedCount: 29,
  },
  {
    id: 'drv-9',
    name: 'Patricia "Pati" Rocha',
    avatar: 'PR',
    vehicle: 'Bike',
    status: 'Pausa',
    phone: '(75) 96412-3210',
    rating: 4.7,
    completedCount: 22,
  },
  {
    id: 'drv-10',
    name: 'Gabriel "Gabi" Souza',
    avatar: 'GS',
    vehicle: 'Van',
    status: 'Disponível',
    phone: '(75) 99312-4455',
    rating: 4.8,
    completedCount: 37,
  },
  {
    id: 'drv-11',
    name: 'Camila "Mila" Cardoso',
    avatar: 'CC',
    vehicle: 'Bike',
    status: 'Disponível',
    phone: '(75) 98711-2299',
    rating: 4.9,
    completedCount: 19,
  },
  {
    id: 'drv-12',
    name: 'Thiago "Tuba" Ramos',
    avatar: 'TR',
    vehicle: 'Moto',
    status: 'Disponível',
    phone: '(75) 96199-3120',
    rating: 4.4,
    completedCount: 8,
  },
  {
    id: 'drv-13',
    name: 'Amanda "Mandinha" Martins',
    avatar: 'AM',
    vehicle: 'Carro',
    status: 'Disponível',
    phone: '(75) 97155-8822',
    rating: 4.8,
    completedCount: 26,
  },
  {
    id: 'drv-14',
    name: 'Renan "Flash" Barbosa',
    avatar: 'RB',
    vehicle: 'Moto',
    status: 'Em Trânsito',
    phone: '(75) 96322-9955',
    rating: 5.0,
    completedCount: 64,
  },
  {
    id: 'drv-15',
    name: 'Leticia "Lê" Vasconcellos',
    avatar: 'LV',
    vehicle: 'Bike',
    status: 'Disponível',
    phone: '(75) 97233-4411',
    rating: 4.9,
    completedCount: 31,
  },
  {
    id: 'drv-16',
    name: 'Clécio "Guerreiro" Silva',
    avatar: 'CS',
    vehicle: 'Moto',
    status: 'Disponível',
    phone: '(75) 96544-2211',
    rating: 5.0,
    completedCount: 42,
  },
];

// Seed Deliveries with updated specs
export const INITIAL_DELIVERIES: Delivery[] = [
  {
    id: 'ent-101',
    address: 'Rua do Cemitério, 172 - Centro',
    clientName: 'Roberto de Souza',
    destinationCity: 'Paulo Afonso - BA (Dentro da Cidade)',
    isNonStandard: true,
    extraSurcharge: 1.00, // 2.50 + 1.00 = 3.50
    driverId: 'drv-1',
    status: 'Em Trânsito',
    value: 3.50,
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    notes: 'Entregar com urgência. Campainha quebrada.',
    coords: { x: 35, y: 40 },
    history: [
      { status: 'Pendente', timestamp: new Date(Date.now() - 45 * 60000).toISOString() },
      { status: 'Em Trânsito', timestamp: new Date(Date.now() - 15 * 60000).toISOString() },
    ],
    paymentStatus: 'Pendente',
  },
  {
    id: 'ent-102',
    address: 'Av. principal, 450 - Centro',
    clientName: 'Julio Cesar Santos',
    destinationCity: 'Delmiro Gouveia - AL',
    isNonStandard: false,
    extraSurcharge: 0.00, // standard pays 3.50
    driverId: 'drv-4',
    status: 'Em Trânsito',
    value: 3.50,
    createdAt: new Date(Date.now() - 60 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    notes: 'Tocar o interfone duas vezes.',
    coords: { x: 45, y: 25 },
    history: [
      { status: 'Pendente', timestamp: new Date(Date.now() - 60 * 60000).toISOString() },
      { status: 'Em Trânsito', timestamp: new Date(Date.now() - 30 * 60000).toISOString() },
    ],
    paymentStatus: 'Pendente',
  },
  {
    id: 'ent-103',
    address: 'Rua do Comércio, 12 - Centro',
    clientName: 'Sofia Alencar',
    destinationCity: 'Mata Grande - AL',
    isNonStandard: false,
    extraSurcharge: 0.00, // 3.50 base rate
    driverId: 'drv-8',
    status: 'Em Trânsito',
    value: 3.50,
    createdAt: new Date(Date.now() - 30 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    notes: 'Não buzinar (bebê dormindo).',
    coords: { x: 28, y: 55 },
    history: [
      { status: 'Pendente', timestamp: new Date(Date.now() - 30 * 60000).toISOString() },
      { status: 'Em Trânsito', timestamp: new Date(Date.now() - 10 * 60000).toISOString() },
    ],
    paymentStatus: 'Pendente',
  },
  {
    id: 'ent-104',
    address: 'Rua da Areia, s/n - Pariconha Centro',
    clientName: 'Marilane Albuquerque',
    destinationCity: 'Pariconha - AL',
    isNonStandard: true,
    extraSurcharge: 2.00, // 5.00 base + 2.00 surcharge = 7.00
    driverId: 'drv-14',
    status: 'Em Trânsito',
    value: 7.00,
    createdAt: new Date(Date.now() - 20 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    notes: 'Urgente! Pacote fora do padrão.',
    coords: { x: 60, y: 35 },
    history: [
      { status: 'Pendente', timestamp: new Date(Date.now() - 20 * 60000).toISOString() },
      { status: 'Em Trânsito', timestamp: new Date(Date.now() - 5 * 60000).toISOString() },
    ],
    paymentStatus: 'Pendente',
  },
  {
    id: 'ent-105',
    address: 'Av. Beira Rio, 890',
    clientName: 'Pedro Cavalcante',
    destinationCity: 'Paulo Afonso - BA (Dentro da Cidade)',
    isNonStandard: false,
    extraSurcharge: 0.00, // Just 2.50 base rate
    driverId: null,
    status: 'Pendente',
    value: 2.50,
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60000).toISOString(),
    notes: 'Próximo ao lago da prefeitura.',
    coords: { x: 40, y: 50 },
    history: [
      { status: 'Pendente', timestamp: new Date(Date.now() - 12 * 60000).toISOString() }
    ],
    paymentStatus: 'Pendente',
  },
  {
    id: 'ent-106',
    address: 'Rua da Capela, 400',
    clientName: 'Fernanda Montenegro',
    destinationCity: 'Glória - BA',
    isNonStandard: false,
    extraSurcharge: 0.00, // 5.00 base rate
    driverId: null,
    status: 'Pendente',
    value: 5.00,
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    notes: 'Deixar com o porteiro.',
    coords: { x: 20, y: 65 },
    history: [
      { status: 'Pendente', timestamp: new Date(Date.now() - 5 * 60000).toISOString() }
    ],
    paymentStatus: 'Pendente',
  },
  {
    id: 'ent-107',
    address: 'Rua Principal de Jatobá, 1500',
    clientName: 'Gabriel Medeiros',
    destinationCity: 'Jatobá - PE',
    isNonStandard: false,
    extraSurcharge: 0.00, // 5.00 base rate
    driverId: 'drv-2',
    status: 'Entregue',
    value: 5.00,
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 60000).toISOString(),
    notes: 'Entregue com sucesso.',
    coords: { x: 15, y: 45 },
    history: [
      { status: 'Pendente', timestamp: new Date(Date.now() - 120 * 60000).toISOString() },
      { status: 'Em Trânsito', timestamp: new Date(Date.now() - 95 * 60000).toISOString() },
      { status: 'Entregue', timestamp: new Date(Date.now() - 40 * 60000).toISOString() },
    ],
    paymentStatus: 'Pago',
    paymentDate: new Date(Date.now() - 39 * 60000).toISOString(),
  },
  {
    id: 'ent-108',
    address: 'Zona comercial, bloco C 12',
    clientName: 'Clara Simoni',
    destinationCity: 'Paulo Afonso - BA (Dentro da Cidade)',
    isNonStandard: false,
    extraSurcharge: 0.00, // 2.50 base rate
    driverId: 'drv-3',
    status: 'Entregue',
    value: 2.50,
    createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 60000).toISOString(),
    notes: 'Loja Central.',
    coords: { x: 30, y: 70 },
    history: [
      { status: 'Pendente', timestamp: new Date(Date.now() - 90 * 60000).toISOString() },
      { status: 'Em Trânsito', timestamp: new Date(Date.now() - 70 * 60000).toISOString() },
      { status: 'Entregue', timestamp: new Date(Date.now() - 25 * 60000).toISOString() },
    ],
    paymentStatus: 'Pendente',
  }
];

